app/controllers/theme_creator/theme_creator_controller.rb
assets/javascripts/discourse/routes/theme-share-key.js.es6
assets/javascripts/discourse/theme-creator-share-route-map.js.es6
config/routes.rb
plugin.rb
spec/theme_creator_controller_spec.rb
spec/user_theme_guardian_spec.rb

`key` column on `themes` table is about to be dropped in core, so we need to stop using it here.
Also `be_success` is deprecated in Rails 5.2 (I think), so I replaced it with `be_successful`

Compatibility with core changes

---

assets/javascripts/discourse/controllers/user-themes-view-modal.js.es6
config/routes.rb
plugin.rb

Sorry for my mistake, PR #4 didn't include color scheme in theme downloads, which is fixed in this PR.
The color scheme is in format of `{colors: [{name: "primary", hex: "222222", default_hex: "222222"}, {name: "secondary", hex: "ffffff", default_hex: "ffffff"}, ...]}`.

FIX: Include color scheme in theme downloads.

---

app/controllers/theme_creator/theme_creator_controller.rb
spec/theme_creator_controller_spec.rb

```text
NoMethodError (undefined method `id' for nil:NilClass)
/var/www/discourse/plugins/discourse-theme-creator/app/controllers/theme_creator/theme_creator_controller.rb:59:in `share_info'
```
This PR correctly handles nonexistent user/theme  when hitting URLs like:
1. `/theme/user-not-found/valid-slug`
2. `/theme/theme-not-found`

FIX: 404 if theme or user does not exist

---

assets/javascripts/discourse/templates/user-themes.hbs
config/locales/client.en.yml

This PR updates the label for the CLI to something more clearer
before 
after

UX: Change the label for the CLI button

---

plugin.rb

The eye icon is used in the API key modal, but it's not added to the sprite sheet. This PR fixes that.

FIX: adds missing eye icon to sprite sheet

---

app/controllers/theme_creator/theme_creator_controller.rb
assets/javascripts/discourse/models/user-theme.js.es6
config/routes.rb
spec/theme_creator_controller_spec.rb

`diff_local_changes` has been removed from core in https://github.com/discourse/discourse/pull/11247

Revert "FIX: users should able to get local theme changes."

---

plugin.rb

The theme previews were regressed after this commit in core: https://github.com/discourse/discourse/commit/8e3691d5370bb95d99fe750f46287763721fcc9c

FIX: theme previews were broken

---

plugin.rb

Ideally a theme would never be attached to a non-existent user, but we can't be sure of that without using foreign keys. This commit updates the serialization logic to handle a missing user gracefully.

FIX: Ensure themes can still be serialized if users are missing

---

plugin.rb

Core recently added the `defer` attribute to all scripts. We need to apply the same here, so that the locale is loaded after the other core JS files. Using the `preload_script_url` helper will match the core behavior, and automatically includes the `defer` attribute.

FIX: Correctly defer loading of admin locale

---

app/controllers/theme_creator/theme_creator_controller.rb

theme-creator has its own security model so we can skip core's admin check

FIX: Update permissions following core change

---

app/controllers/theme_creator/theme_creator_controller.rb

Followup to 985d3ddc. `ensure_staff` is still being used, so we need to skip that as well

FIX: Update permissions following core change (take 2)

---

app/controllers/theme_creator/theme_creator_controller.rb

https://github.com/discourse/discourse/commit/586454bcf1dc56597bff59633a1f61b78ce8d894 removed the `ensure_staff` before_action from the Admin::ThemesController

FIX: Update following core changes

---

assets/javascripts/discourse/templates/user-themes-show.hbs
assets/stylesheets/theme-creator.scss

I'm using the same HTML code as in the regular admin -> customize -> themes page to wrap the button, with additional CSS for the theme creator.
Before:
After:

UX: fix theme actions buttons position alignment

---

assets/javascripts/discourse/templates/modal/user-themes-share-modal.hbs

Remove an empty space in the share URL that prevents copy-pasting a valid share link.
Before:
After:

UX: fix empty space in the share URL

---

assets/javascripts/discourse/templates/modal/user-themes-share-modal.hbs
assets/stylesheets/theme-creator.scss

Fixes the theme settings layout.
Before:
After:

UX: Fix theme settings layout

---

assets/javascripts/discourse/components/modal/user-themes-share-modal.js

A refactor done in https://github.com/discourse/discourse-theme-creator/commit/1f24a3783875b9313f42341fb70f579e91d0a296 hasn't correctly converted this line as it was now acting as if `model` was a property on `this` and not `this.args` which is incorrect.

FIX: ensures stop sharing is working

---

app/controllers/theme_creator/theme_creator_controller.rb
assets/javascripts/discourse/components/user-schema-theme-setting-editor.gjs
assets/javascripts/discourse/components/user-theme-setting-editor.js
assets/javascripts/discourse/models/user-theme-settings.js
assets/javascripts/discourse/models/user-theme.js
assets/javascripts/discourse/routes/user-themes-show-schema.js
assets/javascripts/discourse/templates/user-themes-show-schema.hbs
assets/javascripts/discourse/theme-creator-user-route-map.js
config/routes.rb
spec/system/user_theme_object_setting_spec.rb
spec/system/user_theme_setting_spec.rb
spec/theme_creator_controller_spec.rb

Prior to this fix, editing settings was broken as it was not in line with latest core changes related to object settings.
This commit had the missing bits:
- user accessible objects_setting_metadata endpoint (it was restricted to admins)
- override the various new components/models to handle user themes path instead of admin themes path
This commit also adds specs.

FIX: ensures users can edit settings

---

assets/javascripts/discourse/models/user-theme-settings.js
spec/system/user_theme_setting_spec.rb

The previous test was wrong as using an admin user to test it, moreover it was missing a change in user-theme-settings to ensure that click save from the user themes is correctly calling the user_themes endpoint and not trying to reach for admin endpoints.

FIX: ensures user can save theme setting

---

db/migrate/20201028134841_update_user_api_key_scopes.rb

We are adding the Rails/ReversibleMigrationMethodDefinition cop to rubocop-discourse, this change resolves existing errors under this rule.

DEV: resolve Rails/ReversibleMigrationMethodDefinition errors

---

assets/javascripts/discourse/components/modal/user-themes-share-modal.hbs
assets/javascripts/discourse/components/user-theme-setting-editor.js
assets/javascripts/discourse/templates/components/theme-metadata-field.hbs
assets/javascripts/discourse/templates/user-themes-show.hbs

This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: Update more deprecated Font Awesome icon names

---

app/controllers/theme_creator/theme_creator_controller.rb
spec/theme_creator_controller_spec.rb

See https://meta.discourse.org/t/generate-api-key-in-theme-creator-failed/342247

FIX: use new user api client key system in discourse/discourse

---

assets/javascripts/discourse/components/modal/user-themes-share-modal.hbs
config/locales/client.en.yml
config/locales/server.en.yml

This should also resolve an 'attrs already updated' error we're seeing following a recent ember update

DEV: Switch from legacy TextArea component to native input

---

assets/javascripts/discourse/components/user-schema-theme-setting-editor.gjs
assets/javascripts/discourse/templates/user-themes-show-schema.hbs

Due to the changes in https://github.com/discourse/discourse/commit/4d99c839b6032808c153df1aed752d1a470cb190#diff-276ade29bcc14f26395018ebf94fa8c98b57f161ed6054b5060ad557b13d0e7f
we needed to update imports in the component and update variable naming. Changed how props were passed to the component to match the new structure on the `.hbs` file.

FIX: fix failing specs for user schema theme setting editor
